import Link from "next/link";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Card, CardContent } from "@/components/ui/card"; import { Pagination } from "@/components/common/pagination";
import { alertCommandAction } from "./breaking-alerts.actions"; import type { getAlertListView } from "./breaking-alerts.service";
type View = Awaited<ReturnType<typeof getAlertListView>>;
function href(view: View,page:number){const q=new URLSearchParams({...view.filters,page:String(page)});for(const [k,v] of [...q])if(!v)q.delete(k);return `/admin/alerts?${q}`;}
export function BreakingAlertsList({view,isAdmin}:{view:View;isAdmin:boolean}){return <div className="space-y-4">
  <div className="grid gap-3 sm:grid-cols-3">{[["Current active",view.counts.active],["Upcoming",view.counts.upcoming],["Expired",view.counts.expired]].map(([x,n])=><Card key={x} padding="none"><CardContent className="py-4"><p className="text-sm text-muted-foreground">{x}</p><p className="text-2xl font-semibold">{n}</p></CardContent></Card>)}</div>
  <Card padding="none"><CardContent><form className="grid gap-3 md:grid-cols-3 xl:grid-cols-7"><input name="search" defaultValue={view.filters.search} placeholder="Search alerts" className="min-h-10 rounded-md border px-3 md:col-span-2"/><select name="status" defaultValue={view.filters.status} className="min-h-10 rounded-md border px-3"><option value="">All statuses</option><option value="draft">Draft</option><option value="active">Active</option><option value="archived">Archived</option></select><select name="type" defaultValue={view.filters.type} className="min-h-10 rounded-md border px-3"><option value="">All types</option><option value="emergency">Emergency</option><option value="breaking">Breaking</option><option value="alert">Alert</option></select><select name="language" defaultValue={view.filters.language} className="min-h-10 rounded-md border px-3"><option value="">All languages</option>{view.references.languages.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="sort" defaultValue={view.filters.sort} className="min-h-10 rounded-md border px-3"><option value="updated">Recently updated</option><option value="priority">Priority</option><option value="start_asc">Start time</option></select><Button type="submit">Apply filters</Button></form></CardContent></Card>
  <div className="overflow-x-auto rounded-md border"><table className="w-full min-w-[900px] text-sm"><thead className="border-b bg-muted/50 text-left"><tr><th className="p-3">Alert</th><th>Type</th><th>Status</th><th>Schedule</th><th>Priority</th><th>Actions</th></tr></thead><tbody className="divide-y">{view.items.map(a=><tr key={a.id}><td className="p-3"><Link className="font-medium hover:underline" href={`/admin/alerts/${a.id}`}>{a.title}</Link><p className="text-xs text-muted-foreground line-clamp-1">{a.message}</p></td><td><Badge variant="outline">{a.type}</Badge></td><td><Badge variant="outline">{a.status}{a.status==="active"&&!a.is_active?" · off":""}</Badge></td><td>{new Date(a.start_at).toLocaleString("en-IN")}</td><td>{a.priority}</td><td><form action={alertCommandAction} className="flex gap-1"><input type="hidden" name="id" value={a.id}/>{a.is_active?<Button type="submit" size="sm" variant="outline" name="command" value="deactivate">Deactivate</Button>:<Button type="submit" size="sm" variant="outline" name="command" value="activate">Activate</Button>}<Button type="submit" size="sm" variant="outline" name="command" value="duplicate">Duplicate</Button><Button type="submit" size="sm" variant="outline" name="command" value="archive">Archive</Button>{isAdmin?<Button type="submit" size="sm" variant="destructive" name="command" value="delete">Delete</Button>:null}</form></td></tr>)}</tbody></table></div>
  {view.items.length===0?<p className="rounded-md border border-dashed p-10 text-center text-muted-foreground">No alerts match these filters.</p>:null}
  <Pagination currentPage={view.page} totalPages={view.totalPages} previousHref={view.page>1?href(view,view.page-1):undefined} nextHref={view.page<view.totalPages?href(view,view.page+1):undefined}/>
</div>}
