import assert from "node:assert/strict";
import test from "node:test";
import { createHomepageRendererService } from "./homepage-renderer.service-core.ts";

const legacy={all:[],featured:null,breaking:[],pinnedAlert:null,topHeadlines:[],latest:[],trending:[],categoryRails:[],editorPicks:[]};
const config={configuration:{id:"config",languageId:"lang",locale:"en"},sections:[{id:"s"}]};
function dependencies(overrides={}) { const calls={repository:0,liveTv:0,logs:[]}; return {calls,deps:{loadLegacy:async()=>legacy,loadConfiguration:async()=>{calls.repository++;return config;},composePreview:()=>({locale:"en",sections:[{id:"s",blockId:"latest",title:"Latest",type:"latest-news",renderer:"latest-news",position:0,container:"main",width:"full",configuration:{limit:4}}]}),resolvePayload:(_locale,preview,_legacy,live)=>({locale:"en",sections:preview.sections.map(section=>({...section,data:section.type==="live-tv"?{kind:"live-tv",view:live}:{kind:"stories",stories:[]}}))}),loadLiveTv:async()=>{calls.liveTv++;return {mode:"offline"};},validatePayload:value=>value,renderSection:section=>section.id,log:diagnostic=>calls.logs.push(diagnostic),...overrides}}; }

test("disabled flag returns legacy without querying builder persistence",async()=>{const {calls,deps}=dependencies();const result=await createHomepageRendererService(deps)("en",false);assert.equal(result.kind,"legacy");assert.equal(calls.repository,0);});
test("missing, empty, repository, contract, and renderer failures return the whole legacy homepage",async()=>{for(const overrides of [{loadConfiguration:async()=>null},{composePreview:()=>({locale:"en",sections:[]})},{loadConfiguration:async()=>{throw new Error("db") }},{validatePayload:()=>{throw new Error("invalid") }},{renderSection:()=>{throw new Error("render") }}]){const {calls,deps}=dependencies(overrides);const result=await createHomepageRendererService(deps)("en",true);assert.equal(result.kind,"legacy");assert.equal(result.legacy,legacy);assert.equal(calls.logs.length,1);}});
test("successful configuration returns typed complete builder output and resolves Live TV lazily",async()=>{let fixture=dependencies();let result=await createHomepageRendererService(fixture.deps)("en",true);assert.equal(result.kind,"builder");assert.deepEqual(result.sections.map(x=>[x.type,x.node]),[["latest-news","s"]]);assert.equal(fixture.calls.liveTv,0);fixture=dependencies({composePreview:()=>({locale:"en",sections:[{id:"tv",blockId:"tv",title:"TV",type:"live-tv",renderer:"live-tv",position:0,container:"main",width:"full",configuration:{}}]})});result=await createHomepageRendererService(fixture.deps)("en",true);assert.equal(result.kind,"builder");assert.equal(fixture.calls.liveTv,1);});
